apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test2
  namespace: vault
spec:
  refreshInterval: "15s" # How often this secret is synchronized
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target: 
    name: # If not present, then the secretKey field under data will be used
    creationPolicy: Owner # This will create the secret if it doesn't exist
  data:
    - secretKey: pakistan  
      remoteRef:
        key: islamabad 
        property: islamabad
